title: "intl"
author: "Blog Author"
description: "It's Not Too Late"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true              # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "script.md", title: "Script"}
  - {file : "instructions.md", title: "Instructions"}
  - {url: "https://timetreeapp.com/calendars/SRx7BmTyN7Hw", title: "Timetree"}
  - {url: "https://www.signupgenius.com/go/10c0f4aaeab2fa2fac07-august", title: "Service Work"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:itsnottoolate1030@gmail.com"}
  
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
